[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "test-poetry"
version = "0.1.0"
description = ""
authors = ["Alex Lowe <alex.lowe@canonical.com>"]
readme = "README.md"

[tool.poetry.dependencies]
distro = "==1.8.0"
python = "^3.10"

[tool.poetry.scripts]
mytest = "test_poetry:main"
