# Copyright 2026 Canonical Ltd.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License version 3 as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

"""Groovy templates for Gradle init scripts."""

from textwrap import dedent

INIT_SCRIPT_TEMPLATE = dedent(
    """\
  // init script generated by craft-parts gradle plugin

  // add local maven repo for plugin resolution
  settingsEvaluated {{ settings ->
      settings.pluginManagement {{
          repositories.clear()
          repositories {{
              maven {{ url = uri("{local_maven_repo}") }}
          }}
      }}
  }}

  allprojects {{
      // add local maven repo for project dependency resolution
      buildscript {{
          repositories.clear()
          repositories {{
              maven {{ url = uri("{local_maven_repo}") }}
          }}
      }}

      repositories.clear()
      repositories {{
          maven {{ url = uri("{local_maven_repo}") }}
      }}
  }}

  {publish_block}
"""
)

PUBLISH_BLOCK_TEMPLATE = dedent(
    """\
  // publish to local maven repo
  allprojects {{ Project p ->
      p.pluginManager.apply("maven-publish")
      p.plugins.withId("maven-publish") {{
          p.afterEvaluate {{
              p.publishing {{
                  repositories.clear()
                  repositories {{
                      maven {{
                          url = uri("{publish_maven_repo}")
                      }}
                  }}

                  // generate publication for any missing components
                  p.components.each {{ component ->
                      if (publications.findByName(component.name) == null) {{
                          publications.create(component.name, MavenPublication) {{
                              from component
                          }}
                      }}
                  }}
              }}
          }}
      }}
  }}
"""
)
