# -*- Mode:Python; indent-tabs-mode:nil; tab-width:4 -*-
#
# Copyright 2025 Canonical Ltd.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License version 3 as published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import shutil
import subprocess
import textwrap
from pathlib import Path

import pytest
import yaml
from craft_parts import LifecycleManager, Step
from craft_parts.infos import ProjectInfo

pytestmark = [pytest.mark.java]


@pytest.fixture
def use_gradlew(request, new_dir):
    if not (use_wrapper := request.param):
        Path(new_dir, "gradlew").unlink(missing_ok=True)
    return use_wrapper


def copy_tree(new_dir, copy_dir):
    source_location = Path(__file__).parent / "test_gradle" / copy_dir
    shutil.copytree(source_location, new_dir, dirs_exist_ok=True)
    return Path(new_dir)


@pytest.mark.parametrize("use_gradlew", [True, False], indirect=True)
def test_gradle_plugin(new_dir, partitions, use_gradlew):
    copy_tree(new_dir, "simple")
    part_name = "foo"
    parts_yaml = textwrap.dedent(
        f"""
        parts:
          {part_name}:
            plugin: gradle
            gradle-task: testWrite build
            gradle-init-script: init.gradle
            source: {new_dir}
            build-packages: [openjdk-21-jdk]
            build-snaps:
                - gradle
            build-environment:
                  # This is just because the test environment has multiple java versions and will
                  # use default-jre if unspecified.
                - JAVA_HOME: /usr/lib/jvm/java-21-openjdk-${{CRAFT_ARCH_BUILD_FOR}}
                  # Set GRADLE_USER_HOME dir to the according part's build .gradle dir to avoid
                  # interfering with other tests.
                - GRADLE_USER_HOME: {new_dir}/parts/{part_name}/build/.gradle
            stage-packages: [openjdk-21-jdk]
        """
    )
    parts = yaml.safe_load(parts_yaml)
    lf = LifecycleManager(
        parts,
        application_name="test_gradle",
        cache_dir=new_dir,
        work_dir=new_dir,
        partitions=partitions,
    )
    actions = lf.plan(Step.PRIME)

    with lf.action_executor() as ctx:
        ctx.execute(actions)

    _test_core_gradle_plugin_build_output(project_info=lf.project_info)
    # generated by the init.gradle testWrite task
    assert (
        lf.project_info.dirs.parts_dir / f"{part_name}/build/build" / "test.txt"
    ).exists()


def _test_core_gradle_plugin_build_output(project_info: ProjectInfo) -> None:
    prime_dir = project_info.prime_dir
    java_binary = Path(prime_dir, "bin", "java")
    assert java_binary.is_file()

    output = subprocess.check_output(
        [str(java_binary), "-jar", f"{prime_dir}/jar/build-1.0.jar"], text=True
    )
    assert output.strip() == "Hello from Gradle-built Java"


@pytest.mark.slow
def test_gradle_self_contained(new_dir, partitions):
    copy_tree(new_dir, "self-contained")
    parts = yaml.safe_load((new_dir / "parts.yaml").read_text(encoding="utf-8"))

    lf = LifecycleManager(
        parts,
        application_name="test_gradle_self_contained",
        cache_dir=new_dir,
        work_dir=new_dir,
        partitions=partitions,
    )
    actions = lf.plan(Step.PRIME)
    with lf.action_executor() as ctx:
        ctx.execute(actions)

    backstage = lf.project_info.backstage_dir / "maven-use"
    assert backstage.is_dir()
    assert list(backstage.rglob("*.jar"))
    assert list(backstage.rglob("*.pom"))

    assert list(backstage.rglob("hello-plugin*.jar"))
    assert list(backstage.rglob("hello-plugin*.pom"))
    assert list(backstage.rglob("org.starcraft.hello-plugin.gradle.plugin"))


    jar_dir = lf.project_info.prime_dir / "jar"
    jars = sorted(jar_dir.glob("*.jar"))
    assert jars

    cp = ":".join(str(p) for p in jars)
    output = subprocess.check_output(
        ["java", "-cp", cp, "org.starcraft.HelloCraft"],
        text=True,
    )
    assert output.strip() == "Hello, craft!"
