name: QA
on:
  push:
    branches:
      - "main"
      - "feature/*"
      - "hotfix/*"
      - "release/*"
      - "renovate/*"
  pull_request:

# Cancel existing jobs for this branch/PR
concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  test-other-plugins:
    uses: canonical/starflow/.github/workflows/test-python.yaml@main
    with:
      fast-test-platforms: "[]"
      slow-test-platforms: >
        [
          ["resolute", "amd64"],
        ]
      slow-test-python-versions: '["3.12", "3.14"]'
      lowest-python-platform: '["focal"]'
      lowest-python-version: "3.10"
      pytest-markers: plugin
      setup-vars: NO_JAVA=1 NO_PYTHON=1
